# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: &default
  adapter: postgresql
  encoding: UTF8
  host: localhost
  database: sb_development
  pool: 10
  reaping_frequency: 30


test:
  adapter: postgresql
  encoding: UTF8
  host: localhost
  database: sb_development
  pool: 10
  reaping_frequency: 30

production:
  url: <%=ENV['DATABASE_URL'] %>
  pool: <%= ENV['MAX_THREADS'] %>
